[package]
name = "breedenter-rust"
version = "0.1.0"
edition = "2021"
authors = ["wwng <wwng@2333.me>"]
description = "A rust version of breedenter."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
