[package]
name = "breedenter-rust"
version = "0.1.5"
edition = "2021"
authors = ["wwng <wwng@2333.me>"]
description = "A rust version of breedenter."

[dependencies]
open = "3.2.0"
press-btn-continue = "0.1.1"
